import { NextPage } from 'next'
import Head from 'next/head'

const settings: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        Settings
      </main>
    </>
  )
}

export default settings
