import { NextPage } from 'next'
import Head from 'next/head'

const settings: NextPage = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Settings
    </>
  )
}

export default settings
